module.exports = {
  collectCoverageFrom: [
    '**/*.{ts,tsx}',
    '!**/*.d.ts',
    '!**/node_modules/**',
    '!src/**/*.stories.tsx',
    '!stories/**/*.stories.tsx',
    '!src/lib/log/**',
    '!src/pages/**',
    '!src/lib/ssr.tsx',
    '!src/lib/api/httpClient.ts',
  ],
  setupFilesAfterEnv: ['<rootDir>/setupTests.js'],
  testPathIgnorePatterns: ['/node_modules/', '/.next/'],
  transform: {
    '^.+\\.(js|jsx|ts|tsx)$': '<rootDir>/node_modules/babel-jest',
    '^.+\\.css$': '<rootDir>/config/jest/cssTransform.js',
  },
  transformIgnorePatterns: ['/node_modules/', '^.+\\.module\\.(css|sass|scss)$'],
  moduleNameMapper: {
    '^.+\\.module\\.(css|sass|scss)$': 'identity-obj-proxy',
    '\\.svg$': '<rootDir>/src/__mocks__/svgrMock.ts',
    '@lib/(.*)': '<rootDir>/src/lib/$1',
    '@store/(.*)': '<rootDir>/src/store/$1',
    '@context/(.*)': '<rootDir>/src/context/$1',
    '@atom/(.*)': '<rootDir>/src/components/atoms/$1',
    '@molecule/(.*)': '<rootDir>/src/components/molecules/$1',
    '@organism/(.*)': '<rootDir>/src/components/organisms/$1',
    '@components/(.*)': '<rootDir>/src/components/$1',
    '@form/(.*)': '<rootDir>/src/components/form/$1',
    '@pages/(.*)': '<rootDir>/src/pages/$1',
    '@config/(.*)': '<rootDir>/src/config/$1',
    '@config': '<rootDir>/src/config/index',
    '@assets/(.*)': '<rootDir>/src/assets/$1',
    '__mocks__/(.*)': '<rootDir>/src/__mocks__/$1',
    __mocks__: '<rootDir>/src/__mocks__/index',
  },
}
